trailingComma: 'es5'
tabWidth: 4
singleQuote: true
printWidth: 120
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - ^(^react$|react-dom$|^react-ace$)
  - ^react-router-dom$
  - ^@cloudscape-design/(.*)$
  - <THIRD_PARTY_MODULES>
  - ^@/(.*)$
  - ^[./]
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true